name: Publish

# This workflow is triggered manually via workflow_dispatch
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish
        run: echo Publishing...
